### ISSUE TITLE
Release 1.4 roadmap

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/stpsf#43]
The following items were on the Release 1.3 roadmap (#808) but were deferred beyond that release: 

- [ ]  NIRISS GR700XD model improvements. (not yet a PR) @obi-wan76
- [ ] add some smaller issues regarding improvements in a couple of function @obi-wan76 
- [x] Documentation about PSF subtraction examples @obi-wan76 
- [ ] Notebook example on how to create very large PSFs @obi-wan76

Draft PRs intentionally delayed to after 1.3: 

- [ ] spacetelescope/webbpsf#675 
- [ ] spacetelescope/webbpsf#838

**Comment by mperrin** [comment]
Another stale issue, and release 1.4 was a while ago. So I'm going to close this. But am noting, FYI @obi-wan76, that the GR700XD work is still pending and not yet done, and also you had a to-do note "add some smaller issues regarding improvements in a couple of function" above, and I don't know if you did that or not.   

The create large PSFs notebook was created and is in the docs I see.
